# Generated by Django 2.1.7 on 2019-03-23 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id_game', models.IntegerField()),
                ('id_entity', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('photo', models.CharField(max_length=50, null=True)),
                ('barcode', models.CharField(default=None, max_length=43, null=True)),
                ('rate', models.FloatField(default=5.0)),
                ('id_base_game', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CategoryType')),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Malfunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('data', models.DateField()),
                ('solved', models.BooleanField(default=False)),
                ('id_game_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('returned', models.BooleanField(default=False)),
                ('id_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Game')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
