# Generated by Django 2.1.7 on 2019-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190323_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
