# Generated by Django 2.1.7 on 2019-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190323_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
