# Generated by Django 2.1.7 on 2019-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190323_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='barcode',
            field=models.CharField(max_length=43, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='id_base_game',
            field=models.IntegerField(null=True),
        ),
    ]
