# Generated by Django 2.1.7 on 2019-03-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190323_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecategory',
            name='id_game',
        ),
        migrations.RemoveField(
            model_name='malfunction',
            name='id_game_entity',
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='idgame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='malfunction',
            name='idgameentity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Game'),
            preserve_default=False,
        ),
    ]
